# Generated by Django 5.0.4 on 2024-04-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('icon', models.ImageField(blank=True, height_field=512, null=True, upload_to='', width_field=512)),
                ('date_of_registration', models.DateTimeField(auto_now_add=True, verbose_name='date of registration')),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'user',
            },
        ),
    ]
