# Generated by Django 5.0.4 on 2024-05-17 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
    ]
