# Generated by Django 5.0.4 on 2024-04-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='name',
            new_name='product_name',
        ),
    ]
