# Generated by Django 5.0.4 on 2024-05-17 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_products_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='showcase.brands'),
        ),
        migrations.AlterModelTable(
            name='brands',
            table=None,
        ),
        migrations.AlterModelTable(
            name='categories',
            table=None,
        ),
        migrations.AlterModelTable(
            name='products',
            table=None,
        ),
    ]
