# Generated by Django 5.0.4 on 2024-05-17 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_alter_brands_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Brand'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product'},
        ),
        migrations.AlterModelTable(
            name='brands',
            table='brand',
        ),
        migrations.AlterModelTable(
            name='categories',
            table='category',
        ),
        migrations.AlterModelTable(
            name='products',
            table='product',
        ),
    ]
